Load txt. 
Column selection. 
Save into .csv
Assets selection.
Save into .csv

## First things first

In [1]:
import os, sys
import warnings

if not sys.warnoptions:
    warnings.simplefilter("ignore")

import pandas as pd

main_path = os.getcwd()

In [2]:
colunas = ['Data_Sessão',
'Símbolo_do_Instrumento',
'Sentido_Of_Compra',
'Sequência',
'GenerationID_Of_Compra',
'Cód_do_Evento_da_Of_Compra',
'Hora_Prioridade',
'Ind_de_Prioridade_Of_Compra',
'Preço_Of_Compra',
'Qtd_Total_Of_Compra',
'Qtd_Negociada_Of_Compra',
'Data_Oferta_Compra',
'Data_de_Entrada_Of_Compra',
'Estado_Of_Compra',
'Condição_Oferta',
'Corretora']

In [3]:
list_instrumentos = ['SUZB3                                             ',
'MGLU3                                             ',
'FIBR3                                             ',
'BTOW3                                             ',
'VALE3                                             ',
'BRKM5                                             ',
'EMBR3                                             ',
'PETR4                                             ',
'CPFE3                                             ',
'KLBN4                                             ',
'BRFS3                                             ',
'KROT3                                             ',
'ELET6                                             ',
'QUAL3                                             ',
'UGPA3                                             ',
'ECOR3                                             ',
'ELET3                                             ',
'CCRO3                                             ',
'SBSP3                                             ',
'GOLL4                                             ']

In [5]:
#period = [(10,30), (7, 6), (7, 13)]
#period = [(10,29), (10,8), (11,14),(11,16),(10,22),(10,5),(10,16),(8,7),(9,6),(7,31),(8,22),(9,21),(9,5),(8,28),(11,22)]
#period = [(7,11),(7,13),(7,20),(7,25),(8,10),(8,14),(8,16),(8,21),(8,31)]

period = [(9,11),(9,14),(9,24),(9,27),(10,26)]
for per in period:
    mth, day = per
    load_path = "Bases\\Drty\\NEW\\OFER_CPA_2018{}{}.txt".format(str(mth).zfill(2), str(day).zfill(2))
    load_path = os.path.join(main_path, load_path)
    save_path = "Bases\\CPA\\OFER_CPA_2018{}{}.txt".format(str(mth).zfill(2), str(day).zfill(2))
    save_path = os.path.join(main_path, save_path)
    print(load_path)
    df_cpa = pd.DataFrame()
    for chunk in pd.read_csv(load_path, sep=";",low_memory=False,header=1, chunksize=1000000):
        df_cpa = pd.concat([df_cpa, chunk])
        #print('chunk')
    df_cpa.columns = colunas
    df_cpa = df_cpa[df_cpa["Símbolo_do_Instrumento"].isin(list_instrumentos)] # elimina assets no estudiados
    df_cpa = df_cpa[df_cpa['Cód_do_Evento_da_Of_Compra']==4]
    df_cpa.drop(['Data_Sessão',

    'Sentido_Of_Compra',
    'Sequência',
    'GenerationID_Of_Compra',
    'Cód_do_Evento_da_Of_Compra',

    'Ind_de_Prioridade_Of_Compra',

    'Qtd_Total_Of_Compra',
    'Qtd_Negociada_Of_Compra',
    'Data_Oferta_Compra',
    'Data_de_Entrada_Of_Compra',
    'Estado_Of_Compra',
    'Condição_Oferta',
    'Corretora'],inplace = True, axis = 1)
    
    df_cpa.to_csv(save_path, index=False)
    print(load_path, save_path)

C:\Users\vipac\Desktop\ITAU\ValueAtRisk\Bases\Drty\NEW\OFER_CPA_20180911.txt
C:\Users\vipac\Desktop\ITAU\ValueAtRisk\Bases\Drty\NEW\OFER_CPA_20180911.txt C:\Users\vipac\Desktop\ITAU\ValueAtRisk\Bases\CPA\OFER_CPA_20180911.txt
C:\Users\vipac\Desktop\ITAU\ValueAtRisk\Bases\Drty\NEW\OFER_CPA_20180914.txt
C:\Users\vipac\Desktop\ITAU\ValueAtRisk\Bases\Drty\NEW\OFER_CPA_20180914.txt C:\Users\vipac\Desktop\ITAU\ValueAtRisk\Bases\CPA\OFER_CPA_20180914.txt
C:\Users\vipac\Desktop\ITAU\ValueAtRisk\Bases\Drty\NEW\OFER_CPA_20180924.txt
C:\Users\vipac\Desktop\ITAU\ValueAtRisk\Bases\Drty\NEW\OFER_CPA_20180924.txt C:\Users\vipac\Desktop\ITAU\ValueAtRisk\Bases\CPA\OFER_CPA_20180924.txt
C:\Users\vipac\Desktop\ITAU\ValueAtRisk\Bases\Drty\NEW\OFER_CPA_20180927.txt
C:\Users\vipac\Desktop\ITAU\ValueAtRisk\Bases\Drty\NEW\OFER_CPA_20180927.txt C:\Users\vipac\Desktop\ITAU\ValueAtRisk\Bases\CPA\OFER_CPA_20180927.txt
C:\Users\vipac\Desktop\ITAU\ValueAtRisk\Bases\Drty\NEW\OFER_CPA_20181026.txt
C:\Users\vipac\Desktop\ITAU\ValueAtRisk\Bases\Drty\NEW\OFER_CPA_20181026.txt C:\Users\vipac\Desktop\ITAU\ValueAtRisk\Bases\CPA\OFER_CPA_20181026.txt

In [2]:
df_cpa = pd.read_csv(os.path.join(main_path, r"Bases\Drty\OFER_CPA_20180921.txt"), sep=";",low_memory=False,header=1)

In [3]:
df_cpa.head(5)

,2018-09-21,AALR3,1,000086345026389,000000000204616,001,09:45:18.627000,2147483647,000000000011.610000,000000000000001700,000000000000000000,2018-07-23,2018-07-23 09:45:18,0,0.1,00000003
0,2018-09-21,AALR3 ...,1.0,8.634503e+10,27019829.0,2.0,09:45:05.046000,2.147484e+09,10.51,1900.0,0.0,2018-08-24,2018-08-24 09:45:05,5,0.0,3.0
1,2018-09-21,AALR3 ...,1.0,8.638417e+10,218714.0,1.0,09:45:07.276000,2.147484e+09,9.10,1000.0,0.0,2018-08-20,2018-08-20 09:45:07,0,0.0,3.0
2,2018-09-21,AALR3 ...,1.0,8.639189e+10,26849345.0,1.0,16:58:07.381000,2.147484e+09,7.99,200.0,0.0,2018-08-23,2018-08-23 16:58:07,0,0.0,3.0
3,2018-09-21,AALR3 ...,1.0,8.639505e+10,197375.0,2.0,09:45:07.188000,2.147484e+09,10.00,1000.0,0.0,2018-09-10,2018-09-10 09:45:07,5,0.0,3.0
4,2018-09-21,AALR3 ...,1.0,8.639505e+10,4557452.0,1.0,15:38:36.274000,2.147484e+09,12.00,1000.0,0.0,2018-08-27,2018-08-27 15:38:36,0,0.0,3.0

In [4]:
df_cpa.columns = ['Data_Sessão',
'Símbolo_do_Instrumento',
'Sentido_Of_Compra',
'Sequência',
'GenerationID_Of_Compra',
'Cód_do_Evento_da_Of_Compra',
'Hora_Prioridade',
'Ind_de_Prioridade_Of_Compra',
'Preço_Of_Compra',
'Qtd_Total_Of_Compra',
'Qtd_Negociada_Of_Compra',
'Data_Oferta_Compra',
'Data_de_Entrada_Of_Compra',
'Estado_Of_Compra',
'Condição_Oferta',
'Corretora']

In [6]:
df_cpa = df_cpa[df_cpa["Símbolo_do_Instrumento"].isin(list)] # elimina assets no estudiados

In [8]:
df_cpa[df_cpa['Cód_do_Evento_da_Of_Compra']==4].head()

,Data_Sessão,Símbolo_do_Instrumento,Sentido_Of_Compra,Sequência,GenerationID_Of_Compra,Cód_do_Evento_da_Of_Compra,Hora_Prioridade,Ind_de_Prioridade_Of_Compra,Preço_Of_Compra,Qtd_Total_Of_Compra,Qtd_Negociada_Of_Compra,Data_Oferta_Compra,Data_de_Entrada_Of_Compra,Estado_Of_Compra,Condição_Oferta,Corretora
1975115,2018-09-21,BRFS3 ...,1.0,8.642426e+10,24237238.0,4.0,10:13:29.888000,2.147484e+09,21.5,100.0,100.0,2018-09-21,2018-09-21 10:13:29,2,2.0,114.0
1975152,2018-09-21,BRFS3 ...,1.0,8.642516e+10,24228023.0,4.0,10:12:13.204000,2.147484e+09,21.6,900.0,900.0,2018-09-21,2018-09-21 10:12:13,2,2.0,3.0
1975215,2018-09-21,BRFS3 ...,1.0,8.642516e+10,24165001.0,4.0,10:03:00.008000,2.147484e+09,0.0,200.0,100.0,2018-09-21,2018-09-21 10:03:00,1,2.0,147.0
1975216,2018-09-21,BRFS3 ...,1.0,8.642516e+10,24165004.0,4.0,10:03:00.008000,2.147484e+09,0.0,200.0,200.0,2018-09-21,2018-09-21 10:03:00,2,2.0,147.0
1975229,2018-09-21,BRFS3 ...,1.0,8.642516e+10,24182132.0,4.0,10:06:06.106000,2.147484e+09,21.7,2000.0,1200.0,2018-09-21,2018-09-21 10:06:06,1,2.0,72.0

In [9]:
#df_cpa = df_cpa[df_cpa["Símbolo_do_Instrumento"].isin(list)] # elimina assets no estudiados

df_cpa.drop(['Data_Sessão',

'Sentido_Of_Compra',
'Sequência',
'GenerationID_Of_Compra',
'Cód_do_Evento_da_Of_Compra',

'Ind_de_Prioridade_Of_Compra',

'Qtd_Total_Of_Compra',
'Qtd_Negociada_Of_Compra',
'Data_Oferta_Compra',
'Data_de_Entrada_Of_Compra',
'Estado_Of_Compra',
'Condição_Oferta',
'Corretora'],inplace = True, axis = 1)

In [11]:
df_cpa.to_csv(os.path.join(main_path, r"Bases\CPA\OFER_CPA_20180921.csv"), 
              index=False)

#df_cpa.to_csv(os.path.join(main_path, r"Bases\VDA\OFER_VDA_20181122.csv"), 
#              index=False)